services:
  postgres:
    container_name: postgres_sql
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: rimnaarith
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - fastapi-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fastapi-test
    restart: unless-stopped

networks:
  fastapi-test:
    name: fastapi-test-network
    driver: bridge

volumes:
  fastapi-test:
    name: fastapi-test-volumes