from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column
from uuid import UUID, uuid4
from app.core.database import Base

class User(Base):
  __tablename__ = "users"

  # Primary key (UUID)
  # Generated automatically when creating a new User.
  id: Mapped[UUID] = mapped_column(
    Uuid,
    primary_key=True, 
    default=uuid4
  )

  # Name
  firstname: Mapped[str] = mapped_column(
    String(50),
    nullable=False
  )

  # Name
  lastname: Mapped[str] = mapped_column(
    String(50),
    nullable=False
  )

  # Email address
  email: Mapped[str] = mapped_column(
    String(255),
    unique=True,
    nullable=False,
    index=True,
  )

  # Hashed password
  password: Mapped[str] = mapped_column(
    "password_hash",
    String(255),
    nullable=False,
  )

  # Created timestamp
  # Generated by the database when the row is inserted.
  created_at: Mapped[datetime] = mapped_column(
    DateTime(timezone=True),
    server_default=func.now(), # When inserting a new row, if no value is provided, use the current time.
    nullable=False,
  )

  # Updated timestamp
  # Automatically updated whenever the row changes.
  updated_at: Mapped[datetime] = mapped_column(
    DateTime(timezone=True),
    server_default=func.now(), # When inserting a new row, if no value is provided, use the current time.
    onupdate=func.now(),
    nullable=False,
  )